# DATA SCIENCE INTERNSHIP
## WEEK 2 ASSIGNMENT
---

In [1]:
import pandas as pd
import numpy as np

In [2]:
A1=[11,33,22,44,66,55]
A2=[10,30,20,40,60,50]
arrA1=np.array(A1)
arrA2=np.array(A2)
print(arrA1)
print(arrA2)

[11 33 22 44 66 55]
[10 30 20 40 60 50]


**1. Extract the elements of array A1 from the index 2 to 5**

In [3]:
arrA1[2:5]

array([22, 44, 66])

**2. Reshape the array A1 into (3,2) size**

In [4]:
arr=arrA1.reshape(2,3)
print(arr)

[[11 33 22]
 [44 66 55]]


**3. Join the two arrays A1 and A2.**

In [5]:
arr = np.concatenate((arrA1, arrA2))
print(arr)

[11 33 22 44 66 55 10 30 20 40 60 50]


**4. Split the array A1 into 3 arrays.**

In [6]:
arr = np.array(arrA1)
newarr = np.array_split(arr, 3)
print(newarr)

[array([11, 33]), array([22, 44]), array([66, 55])]


**5. Search for a number 44 in the array A1**

In [7]:
arr = np.array(arrA1)
x = np.where(arr == 44)
print(x)

(array([3], dtype=int64),)


**6. Print all the even numbers of array A1 using search option.**

In [8]:
arr = np.array(arrA1)
for i in range(0,len(arr)):
   if arr[i]%2==0:
    print(arr[np.where(arr==arr[i])])
   else:
    pass

[22]
[44]
[66]


**7. Sort the numbers of array A2.**

In [9]:
arr = np.array(arrA2)
print(np.sort(arr))


[10 20 30 40 50 60]


**8. Filter the odd numbers in the array A1 using filter option.**

In [10]:
arr = np.array(arrA1)
for i in range(0,len(arr)):
   if arr[i]%2!=0:
    print(arr[np.where(arr==arr[i])])
   else:
    pass

[11]
[33]
[55]
